Task 1 soldatov
AberonIMB/LibraryManager pull request #2
Opened 2024-11-08 04:05 UTC by Fotaxis

2024-11-12 14:07 UTC, AberonIMB requested changes

2024-11-12 14:07 UTC, AberonIMB commented on src/main/java/org/example/LibraryConsoleApplication.java
> +                    }
Проверку корректности синтаксиса команд можно вынести в отдельный класс

2024-11-12 14:07 UTC, AberonIMB commented on src/main/java/org/example/service/BookService.java
> +        System.out.println(book.getBookInfo());
Для вывода текста в консоль стоит так же отдельный класс сделать

2024-11-16 13:14 UTC, Fotaxis commented on src/main/java/org/example/LibraryConsoleApplication.java
> +                    }
Добавил класс

2024-11-16 13:14 UTC, Fotaxis commented on src/main/java/org/example/service/BookService.java
> +        System.out.println(book.getBookInfo());
Добавил класс

2024-11-18 19:35 UTC, AberonIMB commented
Ок

2024-11-19 12:53 UTC, AberonIMB requested changes

2024-11-19 12:53 UTC, AberonIMB commented on pom.xml
>                  <artifactId>junit-jupiter-api</artifactId>
Можно обойтись одной библиотекой

2024-11-19 14:00 UTC, Fotaxis commented on pom.xml
>                  <artifactId>junit-jupiter-api</artifactId>
Исправил

2024-11-19 14:02 UTC, AberonIMB commented
ок

2024-11-19 14:03 UTC, merged