Task1
AberonIMB/LibraryManager pull request #3
Opened 2024-11-19 14:07 UTC by AberonIMB

2024-11-19 19:06 UTC, YaEtoTui commented on src/main/resources/hibernate.cfg.xml
> +<hibernate-configuration>
Ух, что-то интересное)

2024-11-19 19:06 UTC, YaEtoTui commented on src/main/java/org/example/model/BookDAO.java
> +public class BookDAO {
не в модели. Точнее там, но быть вместе с entity, лучше так не делать

2024-11-19 19:08 UTC, YaEtoTui commented on src/main/java/org/example/model/Book.java
> +    private int id;
Сейчас это не важно. Но лучше Long

2024-11-19 19:09 UTC, YaEtoTui commented on src/main/java/org/example/model/Book.java
> +public class Book {
сеттеров не будет? То есть менять сущность запрещено?)

2024-11-19 19:14 UTC, YaEtoTui commented
Я еще бы протестировал SyntaxChecker , так как баг может там возникнуть. а вы даже не поймете

2024-11-19 19:20 UTC, YaEtoTui commented
Я бы подумал еще над тестами для других классов. Не все покрыли

2024-11-26 15:15 UTC, Fotaxis commented on src/main/java/org/example/model/Book.java
> +    private int id;
Исправили

2024-11-26 15:17 UTC, Fotaxis commented on src/main/java/org/example/model/Book.java
> +public class Book {
У нас по задаче если меняются какие-то поля, то меняются все сразу. Это сделано через метод setNewData

2024-11-26 15:17 UTC, Fotaxis commented on src/main/java/org/example/model/BookDAO.java
> +public class BookDAO {
Изменили

2024-11-26 15:19 UTC, Fotaxis commented on src/main/resources/hibernate.cfg.xml
> +<hibernate-configuration>
Не понял, но мы пароли не выкладывали, а поменяли их на default. Но возможно было лучше просто оставить их пустыми

2024-11-27 12:35 UTC, YaEtoTui commented on src/main/resources/hibernate.cfg.xml
> +<hibernate-configuration>
Не беспокойтесь) Просто интересная задумка) Редко такое встретишь)

2024-11-27 12:48 UTC, YaEtoTui commented on src/main/java/org/example/DAO/BookDAO.java
> + * DAO класс книг для доступа к данным
package стараемся не писать заглавными)

2024-11-27 12:48 UTC, YaEtoTui commented
1-ое задание принято

2024-12-03 17:03 UTC, vpyzhyanov commented on src/main/resources/hibernate.cfg.xml
> +<hibernate-configuration>
Редко, т.к. xml конфигурации давно устарели) Сейчас модно делать properties

2024-12-03 18:46 UTC, vpyzhyanov requested changes
Задача без тестов приниматься не будет ни при каких обстоятельствах!

Основная логика работы не протестирована (LibraryConsoleApplication и CommandFactory), ни одна команда не протестирована!

2024-12-03 18:46 UTC, vpyzhyanov commented on pom.xml
>          <maven.compiler.source>17</maven.compiler.source>
![image](https://github.com/user-attachments/assets/b02117d8-46f7-4c81-b4a0-880fd98321b4)

Вроде у вашего проекта есть название, странно что тут его нет

2024-12-03 18:46 UTC, vpyzhyanov commented on src/main/java/org/example/LibraryConsoleApplication.java
> +        app.commandsProcess(libraryService, commandFactory);
Тёмная сторона ООП: переусложнили метод main. Насоздавали кучу классов непонятно зачем и для кого. Они тут вообще не нужны. Сервисы - это вообще часть состояния, не надо их выкидывать в параметры. Сервисы параметрами метода быть не могут в принципе.

Весь метод должен выглядеть так:

```java
        LibraryConsoleApplication app = new LibraryConsoleApplication();
        app.commandsProcess();
```

2024-12-03 18:46 UTC, vpyzhyanov commented on src/main/java/org/example/LibraryConsoleApplication.java
> +    private void commandsProcess(LibraryService libraryService, CommandFactory commandFactory) {
метод - это всегда глагол. Тут нет ни одного глагола.

Я бы предложил имя `start`, кажется оно лучше отражает действительность.

2024-12-03 18:46 UTC, vpyzhyanov commented on src/main/java/org/example/LibraryConsoleApplication.java
> +            commandHandler.executeCommand(libraryService, command);
что-то не вижу возможности выхода из приложения

2024-12-03 18:46 UTC, vpyzhyanov commented on src/main/java/org/example/LibraryConsoleApplication.java
> +     * Считывает команду пользователя и разбивает её на название и параметры
даже JavaDoc приглашает вас на тёмную сторону. Перегрузили метод.

Лучше всего всю лишнюю информацию убрать из описания. Создать класс Command, который сам умеет понимать что есть команда, а что аргументы. А вся логика парсинга пусть будет инкапсулирована внутри него. Вот тогда это будет ООП

2024-12-03 18:46 UTC, vpyzhyanov commented on src/main/java/org/example/LibraryConsoleApplication.java
> +        Scanner scanner = new Scanner(System.in);
хмм... меня смущает, что ввод из консоли тут, но вывода я не вижу. Хотя бы других мест создания сканера я не нашёл, это хорошо. Ну ладно смотрим дальше.

2024-12-03 18:46 UTC, vpyzhyanov commented on src/main/java/org/example/LibraryConsoleApplication.java
> +        Pattern pattern = Pattern.compile("[\"“](.*?)[\"”]|(\\S+)");
даже тут уже очевидно, что метод сразу 2 задачи решает.

2024-12-03 18:46 UTC, vpyzhyanov commented on src/main/java/org/example/LibraryConsoleApplication.java
> +        return args.toArray(new String[0]);
массив - наихудший способ передачи коллекции значений. Самый неудобный и не гибкий. Оно вам точно надо?

2024-12-03 18:46 UTC, vpyzhyanov commented on src/main/java/org/example/LibraryConsoleApplication.java
> +import org.example.util.SyntaxChecker;
я уже рассказывал какие опции надо включить при коммите. Почему не включили? Если не хотите включать, то давайте вручную пробегитесь по всем файлам и уберите неиспользуемые импорты руками. Раз вы настолько не ленивые.

2024-12-03 18:46 UTC, vpyzhyanov commented on src/main/java/org/example/util/Printer.java
> +        System.out.println("ID должен быть представлен числом.");
А вот и нашёл вывод в консоль. То, что это единственное место вывода в консоль - уже хорошо. Но тёмную сторону миновать не удалось. Вместе с выводом в консоль класс потянул на себя кучу чужой работы и он страшно перегружен лишним функционалом. Буквально каждый метод тащит как минимум по одной чужой задаче.

Давайте выправляться. Весь этот класс - в мусорку, прям удалите его, надо всё переделать. Будем учиться писать полиморфный код, который легко расширять и поддерживать. Создайте класс, который будет инкапсулировать в себе всю работу с консолью. И ввод и вывод. А ещё лучше выделить интерфейс ввода вывода. Сообщения для пользователя - это работы **обработчиков команд** и больше никого! Например, какой-то там SyntaxChecker не должен лезть общаться с пользователем, у него совсем другая задача.

И тогда сегодня ваш код работает с консоль, а завтра сможет легко работать с любым другим механизмом без каких-либо изменений кода.

2024-12-03 18:46 UTC, vpyzhyanov commented on src/main/java/org/example/util/SyntaxChecker.java
> +    private final Printer printer = new Printer();
1. каждый раз создавать новый экземпляр - это мягко говоря не эффективно.
2. Убираем вообще этот класс отсюда

2024-12-03 18:46 UTC, vpyzhyanov commented on src/main/java/org/example/util/SyntaxChecker.java
> +    public boolean checkAddBookCommandSyntax(String[] command) {
> Класс для проверки синтаксиса команд

Вы точно в этом уверены? Но делает он совсем не это. Он проверяет корректность параметров **КОНКРЕТНОЙ** команды. Что тогда этот метод делает здесь? Добро пожаловать в коллективную безответственность. Это первый и уверенный шаг к "спагетти-коду"

2024-12-03 18:46 UTC, vpyzhyanov commented on src/main/java/org/example/util/SyntaxChecker.java
> +    public boolean checkEditBookCommandSyntax(String[] command) {
да здесь абсолютно все методы такие. Удаляем класс, т.к. само его существование наводит тьму на ООП.

2024-12-03 18:46 UTC, vpyzhyanov commented on src/main/java/org/example/commandHandlers/AddBookCommandHandler.java
> +        return libraryService.getSyntaxChecker().checkAddBookCommandSyntax(command);
Да кому нужна эта инкапсуляция?! Правильно, никому не нужна, в топку её! Ведь ООП без неё можно сделать, правда?! .... Но, похоже, нельзя((

Убираем все эти геттеры

2024-12-03 18:46 UTC, vpyzhyanov commented on src/main/java/org/example/commandHandlers/AddBookCommandHandler.java
> +        }
очень интересно как ведёт себя эта команда в случае, когда она некорректна. Эта "молчаливость" меня совсем не устраивает, а пользователя - тем более. Надо корректно обработать эту ситуацию, а не замалчивать её.

2024-12-03 18:46 UTC, vpyzhyanov commented on src/main/java/org/example/commandHandlers/CommandHandler.java
> +    void executeCommand(LibraryService libraryService, String[] command);
сервисы нужны не для того, чтобы передавать их как параметры. Убираем

2024-12-03 18:46 UTC, vpyzhyanov commented on src/main/java/org/example/DAO/BookDAO.java
> + * DAO класс книг для доступа к данным
Не исправлено!

2024-12-03 18:46 UTC, vpyzhyanov commented on src/main/java/org/example/DAO/BookDAO.java
> +            transaction.commit();
погуглите как делается транзакция правильно. Точно не так. Ну и я рассказывал и показывал как её делать. Вот и повод применить знания.

2024-12-03 18:46 UTC, vpyzhyanov commented on src/main/java/org/example/model/Book.java
> +                && publicationYear == book.publicationYear
мы это уже проходили в задаче на коллекции. И вот опять

2024-12-03 18:46 UTC, vpyzhyanov commented on src/main/java/org/example/service/BookService.java
> +    private final Printer printer;
опять перегруз по функционалу. Убрать это отсюда

Даже в ваш JavaDoc это вообще никак не вписывается

> Класс для работы с книгами в библиотеки, который включает в себя добавление, удаление, редактирование, получение и просмотр всех книг

2024-12-03 18:46 UTC, vpyzhyanov commented on src/main/java/org/example/service/BookService.java
> +     * Получить и вывести книгу по id
такое описание должно было навести на мысли о тёмной стороне

2024-12-03 18:46 UTC, vpyzhyanov commented on src/main/resources/hibernate.cfg.xml
> +        <property name="hibernate.connection.url">jdbc:mysql://localhost:3306/LibraryDB?createDatabaseIfNotExist=true</property>
`createDatabaseIfNotExist=true`

Такие вещи допустимо делать только в тестах. В нормальном приложении их быть не должно. Убираем.

2024-12-03 18:46 UTC, vpyzhyanov commented on src/main/resources/hibernate.cfg.xml
> +        <property name="hibernate.connection.password">default</property>
спалили свой "супер безопасный" пароль

2024-12-03 18:46 UTC, vpyzhyanov commented on src/test/java/BookServiceTest.java
> +        bookService = new BookService(bookDAOMock, new Printer());
`new Printer()` тут быть не должно. Консоль собираетесь тестировать что ли? Протестировать можете, но точно не в этом классе

2024-12-03 18:46 UTC, vpyzhyanov commented on src/test/java/BookServiceTest.java
> +        Mockito.doNothing().when(bookDAOMock).save(Mockito.any(Book.class));
это по умолчанию так, это не надо писать. doNothing нужен только для того, чтобы переопределить ранее заданное поведение.

Актуально и для остальных тестов.

2024-12-03 18:46 UTC, vpyzhyanov commented on src/test/java/BookServiceTest.java
> +        Mockito.when(bookDAOMock.getAll()).thenReturn(Arrays.asList(book1, book2));
`List.of(...)`

2024-12-03 18:46 UTC, vpyzhyanov commented on src/test/java/BookServiceTest.java
> +        bookService.editBook(1L, "Преступление и наказание", "Фёдор Достоевский", 1866);
могли поменять не одно поле, а сразу несколько

2024-12-03 18:46 UTC, vpyzhyanov commented on src/test/java/BookServiceTest.java
> +        runAssertEqualsTest("Преступление и наказание", "Фёдор Достоевский", 1866, book);
проверка выглядит очень странно. Как будь-то сами поменяли книгу, и сами проверили что она изменилось. Что бессмысленно. А оказалось, что сам сервис впал в коллективную безотстветственность. Вместо того, чтобы работать с книгой (сущностью) он работает с примитивами (содержимым книги). Так не делается.

2024-12-03 18:46 UTC, vpyzhyanov commented on src/main/java/org/example/service/BookService.java
> +    public void addBook(String title, String author, int publicationYear) {
После просмотра стало предельно ясно что сервис для работы с книгами вообще не сервис для работы с книгами. Он с какими-то отдельными данными работает а не с книгами. Если так делать, то можно вообще класс Book удалить за ненадобностью. (P.S. не надо этого делать, надо использовать объекты. У нас же ООП всё-таки и первая буква там не просто так добавлена)

2024-12-11 18:05 UTC, Fotaxis commented on src/main/java/org/example/service/BookService.java
> +    public void addBook(String title, String author, int publicationYear) {
Отредактировали класс BookService

2024-12-11 18:05 UTC, Fotaxis commented on src/test/java/BookServiceTest.java
> +        runAssertEqualsTest("Преступление и наказание", "Фёдор Достоевский", 1866, book);
Исправили

2024-12-11 18:05 UTC, Fotaxis commented on src/test/java/BookServiceTest.java
> +        bookService.editBook(1L, "Преступление и наказание", "Фёдор Достоевский", 1866);
Исправили

2024-12-11 18:05 UTC, Fotaxis commented on src/test/java/BookServiceTest.java
> +        Mockito.when(bookDAOMock.getAll()).thenReturn(Arrays.asList(book1, book2));
Исправили

2024-12-11 18:05 UTC, Fotaxis commented on src/test/java/BookServiceTest.java
> +        Mockito.doNothing().when(bookDAOMock).save(Mockito.any(Book.class));
Исправили

2024-12-11 18:05 UTC, Fotaxis commented on src/test/java/BookServiceTest.java
> +        bookService = new BookService(bookDAOMock, new Printer());
Убрали

2024-12-11 18:05 UTC, Fotaxis commented on src/main/resources/hibernate.cfg.xml
> +        <property name="hibernate.connection.password">default</property>
Пароль и логин на самом деле другие, а это текстовые заглушки, мы почему-то сразу не додумались оставить параметры пустыми, сейчас исправились

2024-12-11 18:05 UTC, Fotaxis commented on src/main/resources/hibernate.cfg.xml
> +        <property name="hibernate.connection.url">jdbc:mysql://localhost:3306/LibraryDB?createDatabaseIfNotExist=true</property>
Убрали

2024-12-11 18:05 UTC, Fotaxis commented on src/main/java/org/example/service/BookService.java
> +     * Получить и вывести книгу по id
Исправили

2024-12-11 18:05 UTC, Fotaxis commented on src/main/java/org/example/service/BookService.java
> +    private final Printer printer;
Убрали

2024-12-11 18:05 UTC, Fotaxis commented on src/main/java/org/example/model/Book.java
> +                && publicationYear == book.publicationYear
Исправили

2024-12-11 18:06 UTC, Fotaxis commented on src/main/java/org/example/DAO/BookDAO.java
> +            transaction.commit();
Исправили

2024-12-11 18:06 UTC, Fotaxis commented on src/main/java/org/example/commandHandlers/AddBookCommandHandler.java
> +        }
Исправили

2024-12-11 18:06 UTC, Fotaxis commented on src/main/java/org/example/commandHandlers/AddBookCommandHandler.java
> +        return libraryService.getSyntaxChecker().checkAddBookCommandSyntax(command);
Исправили

2024-12-11 18:07 UTC, Fotaxis commented on src/main/java/org/example/util/SyntaxChecker.java
> +    public boolean checkEditBookCommandSyntax(String[] command) {
Удалили

2024-12-11 18:07 UTC, Fotaxis commented on src/main/java/org/example/util/SyntaxChecker.java
> +    public boolean checkAddBookCommandSyntax(String[] command) {
Добавили классы-валидаторы для всех обработчиков

2024-12-11 18:07 UTC, Fotaxis commented on src/main/java/org/example/util/SyntaxChecker.java
> +    private final Printer printer = new Printer();
Исправили

2024-12-11 18:07 UTC, Fotaxis commented on src/main/java/org/example/util/Printer.java
> +        System.out.println("ID должен быть представлен числом.");
Переработали, добавили интерфейс и класс ввода вывода вместо Printer

2024-12-11 18:07 UTC, Fotaxis commented on src/main/java/org/example/LibraryConsoleApplication.java
> +import org.example.util.SyntaxChecker;
Включили опцию optimize imports

2024-12-11 18:07 UTC, Fotaxis commented on src/main/java/org/example/LibraryConsoleApplication.java
> +        return args.toArray(new String[0]);
Исправили с помощью класса Command

2024-12-11 18:07 UTC, Fotaxis commented on src/main/java/org/example/LibraryConsoleApplication.java
> +        Pattern pattern = Pattern.compile("[\"“](.*?)[\"”]|(\\S+)");
Исправили

2024-12-11 18:07 UTC, Fotaxis commented on src/main/java/org/example/LibraryConsoleApplication.java
> +     * Считывает команду пользователя и разбивает её на название и параметры
Разбили команду, добавили класс

2024-12-11 18:07 UTC, Fotaxis commented on src/main/java/org/example/LibraryConsoleApplication.java
> +            commandHandler.executeCommand(libraryService, command);
Добавили, но не через обработчик, а прямо в цикле, для возможности тестирования LibraryConsoleApplication

2024-12-11 18:07 UTC, Fotaxis commented on src/main/java/org/example/LibraryConsoleApplication.java
> +    private void commandsProcess(LibraryService libraryService, CommandFactory commandFactory) {
Исправили

2024-12-11 18:07 UTC, Fotaxis commented on src/main/java/org/example/LibraryConsoleApplication.java
> +        app.commandsProcess(libraryService, commandFactory);
Исправили main

2024-12-11 18:07 UTC, Fotaxis commented on pom.xml
>          <maven.compiler.source>17</maven.compiler.source>
Изменили название

2024-12-11 18:15 UTC, Fotaxis commented on src/main/java/org/example/commandHandlers/CommandHandler.java
> +    void executeCommand(LibraryService libraryService, String[] command);
Не поняли как нужно перестроить приложение так, чтобы не пришлось передавать обработчикам LibraryService.  Только если оборачивать LibraryService в контекст, но не уверены, что это сильно отличается от простой передачи LibraryService

2024-12-15 20:05 UTC, vpyzhyanov approved these changes
Не все замечания были исправлены правильно. Тем не менее задача принята, как исправите последние замечания, можете мёрджить.

Оценка:

- ООП: 4 балла (коллективная безответственность как была, так и осталась)
- Git: 3 балла

2024-12-15 20:05 UTC, vpyzhyanov commented on src/main/java/org/example/LibraryConsoleApplication.java
> +        this.commandFactory = new CommandFactory(ioHandler, libraryService);
дублирование кода. Надо было переиспользовать конструктор

2024-12-15 20:05 UTC, vpyzhyanov commented on src/main/java/org/example/CommandFactory.java
> +        CommandValidator addBookCommandValidator = new AddBookCommandValidator();
Пишу замечание, которое уже было. Я уже писал про аргументы конструкторов и коллективную безответственность. И вот она опять. За это вы теряете один балл.

AddBookCommandValidator нужен только для AddBookCommandHandler. И внутри CommandFactory это знать и, тем более, управлять этим, вовсе не обязательно. Каждая команда сама прекрасно знает в каком формате должны прийти ей параметры, пусть сама и проверяет. Неправильно выносить это куда-либо, хоть в CommandFactory, хоть в отдельный класс. Суть не меняется.

По сути замечание исправлено неправильно. Как была коллективная безответственность, так и осталась.

![image](https://github.com/user-attachments/assets/747be443-4df9-4ed6-8009-79700ecc85f2)

2024-12-15 20:05 UTC, vpyzhyanov commented on src/main/java/org/example/CommandFactory.java
> +        CommandValidator commandWithoutParamsValidator = new CommandsWithoutParamsValidator();
Единственный объект, который используется в нескольких классов - это CommandsWithoutParamsValidator. Но его тоже надо определить внутри каждой конкретной команды, где он явно нужен. И ничего страшного, что экземпляры у них будут дублироваться. Намного важнее поддерживать правильную ответственность.

Да и сегодня этих команд нет параметров, а завтра у одной из них будет параметр, то что вы будете делать? Переписывать весь CommandFactory? Не надо так. Надо переписывать только ту команду, которая реально изменилась и больше ничего.

2024-12-15 20:05 UTC, vpyzhyanov commented on src/main/java/org/example/LibraryConsoleApplication.java
> +    private final LibraryService libraryService;
не используется

2024-12-15 20:05 UTC, vpyzhyanov commented on src/main/java/org/example/service/BookService.java
> +    public void editBook(Book book, String title, String author, int publicationYear) {
> А оказалось, что сам сервис впал в коллективную безотстветственность. Вместо того, чтобы работать с книгой (сущностью) он работает с примитивами (содержимым книги). Так не делается.

Не исправлено. Сервис по прежнему работает с примитивами. Правильно было передавать только один параметр `Book book`. Все изменения самого объекта надо делать снаружи. Здесь лишь сохранение этих изменений.

2024-12-15 20:06 UTC, vpyzhyanov commented on src/main/java/org/example/util/SyntaxChecker.java
> +    public boolean checkAddBookCommandSyntax(String[] command) {
исправлено неправильно. Проблема как была, так и осталась. Просто приобрела немного другую форму.

2024-12-15 20:06 UTC, vpyzhyanov commented on src/main/java/org/example/commandHandlers/CommandHandler.java
> +    void executeCommand(LibraryService libraryService, String[] command);
А говорите не поняли. Сейчас же его нет

2024-12-15 20:06 UTC, vpyzhyanov commented on src/main/java/org/example/DAO/BookDAO.java
> +            transaction.commit();
Похоже я рассказывал куда-то в пустоту(((( Понятие транзакционности не дошло до адресата(((

2024-12-15 20:06 UTC, vpyzhyanov commented on src/test/java/BookServiceTest.java
> +        runAssertEqualsTest("Преступление и наказание", "Фёдор Достоевский", 1866, book);
не исправлено. Как примитивы были, так и остались

2024-12-20 17:59 UTC, merged

2024-12-22 21:45 UTC, Fotaxis commented on src/main/java/org/example/service/BookService.java
> +    public void editBook(Book book, String title, String author, int publicationYear) {
Исправили

2024-12-22 21:45 UTC, Fotaxis commented on src/main/java/org/example/LibraryConsoleApplication.java
> +    private final LibraryService libraryService;
Исправил

2024-12-22 21:45 UTC, Fotaxis commented on src/main/java/org/example/CommandFactory.java
> +        CommandValidator commandWithoutParamsValidator = new CommandsWithoutParamsValidator();
Исправил

2024-12-22 21:45 UTC, Fotaxis commented on src/main/java/org/example/CommandFactory.java
> +        CommandValidator addBookCommandValidator = new AddBookCommandValidator();
Исправил

2024-12-22 21:45 UTC, Fotaxis commented on src/main/java/org/example/LibraryConsoleApplication.java
> +        this.commandFactory = new CommandFactory(ioHandler, libraryService);
Исправил

2024-12-22 21:46 UTC, Fotaxis commented on src/test/java/BookServiceTest.java
> +        runAssertEqualsTest("Преступление и наказание", "Фёдор Достоевский", 1866, book);
Исправил

2024-12-23 14:33 UTC, Fotaxis commented on src/main/java/org/example/DAO/BookDAO.java
> +            transaction.commit();
Я помню, вы рассказывали, что транзакции нужны для группы операций, чтобы при ошибке где-то в одном месте можно было бы откатить все операции сразу. Поэтому, если операция одна, то транзакции не обязательны. Но я не смогу полностью разобраться, из-за чего все методы изменения БД не модифицировали её без использования транзакций. Также, например, persist вместо устаревшего save не только не создавал сущность в БД, но и не присваивал ID, как это делал save